# RSNA 2025 Intracranial Aneurysm Detection - Binary Classification Training Configuration

# Training mode
training_mode: "binary"

# Model settings
model:
  architecture: "tf_efficientnet_b0"  # tf_efficientnet_b0, tf_efficientnet_b5, resnet50, etc.
  num_classes: 1  # Binary classification (aneurysm present/absent)
  in_channels: 5  # 2.5D window length
  pretrained: true

# Training settings
training:
  epochs: 10  # Same as multiclass
  batch_size: 64  # Same as multiclass
  learning_rate: 1.0e-4  # Same as multiclass
  num_folds: 5
  use_cv: true
  mixed_precision: true
  gradient_accumulation_steps: 1
  
  # Loss settings
  loss:
    name: "BCEWithLogitsLoss"
    params:
      reduction: "mean"
      # pos_weight: null  # Uncomment and set for class balancing if needed
  
  # Optimizer settings
  optimizer:
    type: "adam"
    weight_decay: 0.01
    betas: [0.9, 0.999]
  
  # Scheduler settings
  scheduler:
    type: "cosine"
    warmup_epochs: 1  # Same as multiclass
    min_lr: 1.0e-6

# Data settings
data:
  img_size: 224
  window_offsets: [-2, -1, 0, 1, 2]  # 5-slice window
  roi_box_fraction: 0.15  # Not used in binary but kept for compatibility
  roi_min_pixels: 24  # Not used in binary but kept for compatibility
  modalities: ["CTA", "MRA", "MRI T2", "MRI T1post"]  # Use all available modalities
  
  # Augmentation settings (same as multiclass)
  augmentation:
    horizontal_flip: 0.5
    affine:
      scale: [0.95, 1.05]
      translate_percent: 0.05
      rotate: [-10, 10]
      probability: 0.5  # Same as multiclass
    gaussian_noise:
      var_limit: [0.01, 0.05]
      probability: 0.2  # Same as multiclass
    motion_blur:
      blur_limit: 3
      probability: 0.1  # Same as multiclass

# Paths
paths:
  data_dir: "/workspace/Datasets/rsna-intracranial-aneurysm-detection"
  cache_dir: "/workspace/Datasets/rsna-intracranial-aneurysm-detection/processed_data/2_5d_volumes_full"
  train_csv: "/workspace/Datasets/rsna-intracranial-aneurysm-detection/train.csv"
  localizers_csv: "/workspace/Datasets/rsna-intracranial-aneurysm-detection/train_localizers.csv"  # Not used in binary but kept for compatibility
  output_dir: "models"

# System settings
system:
  num_workers: 8
  device: "cuda"  # "cuda" or "cpu"
  seed: 42
  
# Validation settings
validation:
  metric: "auc"  # Simple ROC AUC for binary classification
  save_best_only: true
  patience: 3  # Same as multiclass
  
# Logging settings
logging:
  log_level: "INFO"
  log_file: "binary_training.log"
  wandb:
    enabled: false
    project: "rsna-aneurysm-detection-binary"
    entity: null

# Debug settings
debug:
  enabled: false
  subset_per_class: 50  # Same as multiclass
  fast_dev_run: false  # Run single batch for debugging
